# Generated by Django 3.1.7 on 2021-04-17 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='descriptin',
            new_name='description',
        ),
    ]
